# Generated by Django 4.0.2 on 2024-05-14 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_link',
            field=models.CharField(default='exit', max_length=150),
            preserve_default=False,
        ),
    ]
